from robo_gym.envs.mir100.mir100 import NoObstacleNavigationMir100Sim
from robo_gym.envs.mir100.mir100 import NoObstacleNavigationMir100Rob
from robo_gym.envs.mir100.mir100 import ObstacleAvoidanceMir100Sim
from robo_gym.envs.mir100.mir100 import ObstacleAvoidanceMir100Rob

from robo_gym.envs.ur10.ur10 import EndEffectorPositioningUR10Sim
from robo_gym.envs.ur10.ur10 import EndEffectorPositioningUR10Rob
from robo_gym.envs.ur10.ur10 import EndEffectorPositioningUR10DoF5Sim
from robo_gym.envs.ur10.ur10 import EndEffectorPositioningUR10DoF5Rob
from robo_gym.envs.ur5.ur5 import EndEffectorPositioningUR5Sim
from robo_gym.envs.ur5.ur5 import EndEffectorPositioningUR5Rob
from robo_gym.envs.ur5.ur5 import EndEffectorPositioningUR5DoF5Sim
from robo_gym.envs.ur5.ur5 import EndEffectorPositioningUR5DoF5Rob
from robo_gym.envs.ur5.ur5_avoidance import MovingBoxTargetUR5Sim
from robo_gym.envs.ur5.ur5_avoidance import MovingBoxTargetUR5Rob
from robo_gym.envs.ur5.ur5_avoidance import MovingBoxTargetUR5DoF3Sim
from robo_gym.envs.ur5.ur5_avoidance import MovingBoxTargetUR5DoF3Rob
from robo_gym.envs.ur5.ur5_avoidance import MovingBoxTargetUR5DoF5Sim
from robo_gym.envs.ur5.ur5_avoidance import MovingBoxTargetUR5DoF5Rob
from robo_gym.envs.ur5.ur5_avoidance import MovingBox3DSplineTargetUR5Sim
from robo_gym.envs.ur5.ur5_avoidance import MovingBox3DSplineTargetUR5Rob
from robo_gym.envs.ur5.ur5_avoidance import MovingBox3DSplineTargetUR5DoF3Sim
from robo_gym.envs.ur5.ur5_avoidance import MovingBox3DSplineTargetUR5DoF3Rob
from robo_gym.envs.ur5.ur5_avoidance import MovingBox3DSplineTargetUR5DoF5Sim
from robo_gym.envs.ur5.ur5_avoidance import MovingBox3DSplineTargetUR5DoF5Rob

from robo_gym.envs.ur5.ur5_avoidance import Moving2Box3DSplineTargetUR5Sim
from robo_gym.envs.ur5.ur5_avoidance import Moving2Box3DSplineTargetUR5Rob
from robo_gym.envs.ur5.ur5_avoidance import Moving2Box3DSplineTargetUR5DoF3Sim
from robo_gym.envs.ur5.ur5_avoidance import Moving2Box3DSplineTargetUR5DoF3Rob
from robo_gym.envs.ur5.ur5_avoidance import Moving2Box3DSplineTargetUR5DoF5Sim
from robo_gym.envs.ur5.ur5_avoidance import Moving2Box3DSplineTargetUR5DoF5Rob

from robo_gym.envs.ur5.ur5_1o_2p_avoidance import ObstacleAvoidance1Box2PointsUR5Sim
from robo_gym.envs.ur5.ur5_1o_2p_avoidance import ObstacleAvoidance1Box2PointsUR5Rob
from robo_gym.envs.ur5.ur5_1o_2p_avoidance import ObstacleAvoidance1Box2PointsUR5DoF3Sim
from robo_gym.envs.ur5.ur5_1o_2p_avoidance import ObstacleAvoidance1Box2PointsUR5DoF3Rob
from robo_gym.envs.ur5.ur5_1o_2p_avoidance import ObstacleAvoidance1Box2PointsUR5DoF5Sim
from robo_gym.envs.ur5.ur5_1o_2p_avoidance import ObstacleAvoidance1Box2PointsUR5DoF5Rob

from robo_gym.envs.ur5.ur5_2o_2p_avoidance import ObstacleAvoidance2Box2PointsUR5Sim
from robo_gym.envs.ur5.ur5_2o_2p_avoidance import ObstacleAvoidance2Box2PointsUR5Rob
from robo_gym.envs.ur5.ur5_2o_2p_avoidance import ObstacleAvoidance2Box2PointsUR5DoF3Sim
from robo_gym.envs.ur5.ur5_2o_2p_avoidance import ObstacleAvoidance2Box2PointsUR5DoF3Rob
from robo_gym.envs.ur5.ur5_2o_2p_avoidance import ObstacleAvoidance2Box2PointsUR5DoF5Sim
from robo_gym.envs.ur5.ur5_2o_2p_avoidance import ObstacleAvoidance2Box2PointsUR5DoF5Rob


from robo_gym.envs.ur5.ur5_1o_1p_vox_avoidance import ObstacleAvoidance1Box1PointsVoxelOccupancyUR5Sim
from robo_gym.envs.ur5.ur5_1o_1p_vox_avoidance import ObstacleAvoidance1Box1PointsVoxelOccupancyUR5Rob
from robo_gym.envs.ur5.ur5_1o_1p_vox_avoidance import ObstacleAvoidance1Box1PointsVoxelOccupancyUR5DoF3Sim
from robo_gym.envs.ur5.ur5_1o_1p_vox_avoidance import ObstacleAvoidance1Box1PointsVoxelOccupancyUR5DoF3Rob
from robo_gym.envs.ur5.ur5_1o_1p_vox_avoidance import ObstacleAvoidance1Box1PointsVoxelOccupancyUR5DoF5Sim
from robo_gym.envs.ur5.ur5_1o_1p_vox_avoidance import ObstacleAvoidance1Box1PointsVoxelOccupancyUR5DoF5Rob

from robo_gym.envs.ur5.ur5_fixed_traj_1o_1p_avoidance import FixedTraj1Box1PointsUR5Sim
from robo_gym.envs.ur5.ur5_fixed_traj_1o_1p_avoidance import FixedTraj1Box1PointsUR5Rob
from robo_gym.envs.ur5.ur5_fixed_traj_1o_1p_avoidance import FixedTraj1Box1PointsUR5DoF5Sim
from robo_gym.envs.ur5.ur5_fixed_traj_1o_1p_avoidance import FixedTraj1Box1PointsUR5DoF5Rob

from robo_gym.envs.ur5.ur5_avoid_B_moving_robot import ObstacleAvoidanceVarB1Box1PointUR5Sim
from robo_gym.envs.ur5.ur5_avoid_B_moving_robot import ObstacleAvoidanceVarB1Box1PointUR5Rob
from robo_gym.envs.ur5.ur5_avoid_B_moving_robot import ObstacleAvoidanceVarB1Box1PointUR5DoF3Sim
from robo_gym.envs.ur5.ur5_avoid_B_moving_robot import ObstacleAvoidanceVarB1Box1PointUR5DoF3Rob
from robo_gym.envs.ur5.ur5_avoid_B_moving_robot import ObstacleAvoidanceVarB1Box1PointUR5DoF5Sim
from robo_gym.envs.ur5.ur5_avoid_B_moving_robot import ObstacleAvoidanceVarB1Box1PointUR5DoF5Rob

from robo_gym.envs.ur5.ur5_avoid_B_10points_moving_robot import ObstacleAvoidanceVarB10Points1Box1PointUR5Sim
from robo_gym.envs.ur5.ur5_avoid_B_10points_moving_robot import ObstacleAvoidanceVarB10Points1Box1PointUR5Rob
from robo_gym.envs.ur5.ur5_avoid_B_10points_moving_robot import ObstacleAvoidanceVarB10Points1Box1PointUR5DoF3Sim
from robo_gym.envs.ur5.ur5_avoid_B_10points_moving_robot import ObstacleAvoidanceVarB10Points1Box1PointUR5DoF3Rob
from robo_gym.envs.ur5.ur5_avoid_B_10points_moving_robot import ObstacleAvoidanceVarB10Points1Box1PointUR5DoF5Sim
from robo_gym.envs.ur5.ur5_avoid_B_10points_moving_robot import ObstacleAvoidanceVarB10Points1Box1PointUR5DoF5Rob

from robo_gym.envs.ur5.ur5_avoid_B_traj01_moving_robot import ObstacleAvoidanceVarBTraj011Box1PointUR5Sim
from robo_gym.envs.ur5.ur5_avoid_B_traj01_moving_robot import ObstacleAvoidanceVarBTraj011Box1PointUR5Rob
from robo_gym.envs.ur5.ur5_avoid_B_traj01_moving_robot import ObstacleAvoidanceVarBTraj011Box1PointUR5DoF3Sim
from robo_gym.envs.ur5.ur5_avoid_B_traj01_moving_robot import ObstacleAvoidanceVarBTraj011Box1PointUR5DoF3Rob
from robo_gym.envs.ur5.ur5_avoid_B_traj01_moving_robot import ObstacleAvoidanceVarBTraj011Box1PointUR5DoF5Sim
from robo_gym.envs.ur5.ur5_avoid_B_traj01_moving_robot import ObstacleAvoidanceVarBTraj011Box1PointUR5DoF5Rob

from robo_gym.envs.ur5.ur5_avoid_C_pickplace_3 import ObstacleAvoidanceVarCPickplace31Box1PointUR5Sim
from robo_gym.envs.ur5.ur5_avoid_C_pickplace_3 import ObstacleAvoidanceVarCPickplace31Box1PointUR5Rob
from robo_gym.envs.ur5.ur5_avoid_C_pickplace_3 import ObstacleAvoidanceVarCPickplace31Box1PointUR5DoF3Sim
from robo_gym.envs.ur5.ur5_avoid_C_pickplace_3 import ObstacleAvoidanceVarCPickplace31Box1PointUR5DoF3Rob
from robo_gym.envs.ur5.ur5_avoid_C_pickplace_3 import ObstacleAvoidanceVarCPickplace31Box1PointUR5DoF5Sim
from robo_gym.envs.ur5.ur5_avoid_C_pickplace_3 import ObstacleAvoidanceVarCPickplace31Box1PointUR5DoF5Rob

from robo_gym.envs.ur5.ur5_iros_v01 import IrosEnv01UR5Sim
from robo_gym.envs.ur5.ur5_iros_v01 import IrosEnv01UR5Rob
from robo_gym.envs.ur5.ur5_iros_v01 import IrosEnv01UR5DoF3Sim
from robo_gym.envs.ur5.ur5_iros_v01 import IrosEnv01UR5DoF3Rob
from robo_gym.envs.ur5.ur5_iros_v01 import IrosEnv01UR5DoF5Sim
from robo_gym.envs.ur5.ur5_iros_v01 import IrosEnv01UR5DoF5Rob

from robo_gym.envs.ur5.ur5_iros_v02 import IrosEnv02UR5Sim
from robo_gym.envs.ur5.ur5_iros_v02 import IrosEnv02UR5Rob
from robo_gym.envs.ur5.ur5_iros_v02 import IrosEnv02UR5DoF3Sim
from robo_gym.envs.ur5.ur5_iros_v02 import IrosEnv02UR5DoF3Rob
from robo_gym.envs.ur5.ur5_iros_v02 import IrosEnv02UR5DoF5Sim
from robo_gym.envs.ur5.ur5_iros_v02 import IrosEnv02UR5DoF5Rob

from robo_gym.envs.ur5.ur5_iros_v02 import IrosEnv02UR5FixObstacleTrajDoF5Sim
from robo_gym.envs.ur5.ur5_iros_v02 import IrosEnv02UR5FixObstacleTrajDoF5Rob

from robo_gym.envs.ur5.ur5_iros_ablation_models_test import AblationTestEnvDoF5Sim

from robo_gym.envs.ur5.ur5_iros_v03 import IrosEnv03UR5TrainingDoF5Sim
from robo_gym.envs.ur5.ur5_iros_v03 import IrosEnv03UR5TrainingDoF5Rob

from robo_gym.envs.ur5.ur5_iros_v03 import IrosEnv03UR5TestDoF5Sim
from robo_gym.envs.ur5.ur5_iros_v03 import IrosEnv03UR5TestDoF5Rob

from robo_gym.envs.ur5.ur5_iros_v03 import IrosEnv03UR5TestFixedSplinesDoF5Sim
from robo_gym.envs.ur5.ur5_iros_v03 import IrosEnv03UR5TestFixedSplinesDoF5Rob